Defaults: &defaults
  STAGE_FIRST_FRAME: !!python/int 0
  STAGE_SECOND_FRAME: !!python/int  1
  STAGE_DEFAULT_FRAME: !!python/int  2
  K_MIN_FEATURES: !!python/int  1200
  W: !!python/int 1920
  H: !!python/int 1080
  PIN_HOLE_PARAMS:
    fx: !!python/float 1263.1578
    fy: !!python/int 1125
    cx: !!python/int 960
    cy: !!python/int 540


FAST_PARAMS: &fast
  threshold: !!python/int 10
  nonmaxSuppression: !!python/bool True


ORB_PARAMS: &orb
  nfeatures: !!python/int 5000


BRIEF_PARAMS: &brief
  use_orientation: !!python/bool True

SIFT_PARAMS: &sift
  nOctaveLayers: !!python/int 3
  contrastThreshold: !!python/float 0.04
  edgeThreshold: !!python/int 10
  sigma: !!python/float 1.6


LK_PARAMS: &lk
  winSize: !!python/tuple [21, 21]
  maxLevel: !!python/int 6
  criteria: !!python/tuple [2, 1, 30, 0.01]  # (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 30, 0.01)
  flags: !!python/int 8                    # cv2.OPTFLOW_LK_GET_MIN_EIGENVALS
  minEigThreshold: !!python/float 0.0001 # 1e-4


FLANN_PARAMS:
  NON_SIFT: &flann-not-sift
    index_params:
      algorithm: !!python/int 6
      table_number: !!python/int 6
      key_size: !!python/int 12
      multi_probe_level: !!python/int 1
    search_params:
      checks: !!python/int 50
  SIFT: &flann-sift
    index_params:
      algorithm: !!python/int 0
      trees: !!python/int 5
    search_params:
      checks: !!python/int 50


EXPERIMENT_1:
  name: !!python/str 'FAST-NONE-OpticalFlow'
  correspondence_method: !!python/str 'tracking'
  detector: !!python/str 'FAST'
  detector_params: *fast
  extractor: !!python/none None
  extractor_params: !!python/none None
  lk_params: *lk
  flann_params: !!python/none None
  k_min_features: !!python/int 1200


EXPERIMENT_2:
  name: !!python/str 'ORB-BRIEF-FLANN'
  correspondence_method: !!python/str 'matching'
  detector: !!python/str 'ORB'
  detector_params: *orb
  extractor: !!python/str 'BRIEF'
  extractor_params: *brief
  lk_params: !!python/none None
  flann_params: *flann-not-sift
  k_min_features: !!python/none None

EXPERIMENT_3:
  name: !!python/str 'ORB-SIFT-FLANN'
  correspondence_method: !!python/str 'matching'
  detector: !!python/str 'ORB'
  detector_params: *orb
  extractor: !!python/str 'SIFT'
  extractor_params: *sift
  lk_params: !!python/none None
  flann_params: *flann-sift
  k_min_features: !!python/none None

