DEFAULTS: &defaults
  ANNOTATIONS: !!python/str './data/transformed_ground_truth_vol2.txt'
  IMAGES: !!python/str 'data/images_v1/*.jpg'
  W: !!python/int 1920
  H: !!python/int 1080
  PIN_HOLE_PARAMS:
    fx: !!python/float 1263.1578
    fy: !!python/int 1125
    cx: !!python/int 960
    cy: !!python/int 540

SHI_TOMASI_PARAMS: &shi-tomasi
  maxCorners: !!python/int 300
  qualityLevel: !!python/float 0.03
  minDistance: !!python/int 50
  blocksize: !!python/int 10

FAST_PARAMS: &fast
  threshold: !!python/int 10
  nonmaxSuppression: !!python/bool True

ORB_PARAMS: &orb
  nfeatures: !!python/int 5000

BRIEF_PARAMS: &brief
  use_orientation: !!python/bool True

SIFT_PARAMS: &sift
  nfeatures: !!python/int 5000
  nOctaveLayers: !!python/int 3
  contrastThreshold: !!python/float 0.04
  edgeThreshold: !!python/int 10
  sigma: !!python/float 1.6


LK_PARAMS: &lk
  winSize: !!python/tuple [21, 21]
  maxLevel: !!python/int 6
  criteria: !!python/tuple [2, 1, 30, 0.01]  # (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 30, 0.01)
  flags: !!python/int 8                    # cv2.OPTFLOW_LK_GET_MIN_EIGENVALS
  minEigThreshold: !!python/float 0.0001 # 1e-4


FLANN_PARAMS:
  NON_SIFT: &flann-not-sift
    index_params:
      algorithm: !!python/int 6
      table_number: !!python/int 6
      key_size: !!python/int 12
      multi_probe_level: !!python/int 1
    search_params:
      checks: !!python/int 50
  SIFT: &flann-sift
    index_params:
      algorithm: !!python/int 0
      trees: !!python/int 5
    search_params:
      checks: !!python/int 50

EXPERIMENT_0:
  name: !!python/str 'ShiTomasi-NONE-OpticalFlow'
  correspondence_method: !!python/str 'tracking'
  detector: !!python/str 'SHI-TOMASI'
  detector_params: *shi-tomasi
  extractor: !!python/none None
  extractor_params: !!python/none None
  lk_params: *lk
  flann_params: !!python/none None
  k_min_features: !!python/int 2000
  toggle_morphology: !!python/bool False

EXPERIMENT_1:
  name: !!python/str 'FAST-NONE-OpticalFlow'
  correspondence_method: !!python/str 'tracking'
  detector: !!python/str 'FAST'
  detector_params: *fast
  extractor: !!python/none None
  extractor_params: !!python/none None
  lk_params: *lk
  flann_params: !!python/none None
  k_min_features: !!python/int 1200
  toggle_morphology: !!python/bool False

EXPERIMENT_2:
  name: !!python/str 'SIFT-NONE-OpticalFlow'
  correspondence_method: !!python/str 'tracking'
  detector: !!python/str 'SIFT'
  detector_params: *sift
  extractor: !!python/none None
  extractor_params: !!python/none None
  lk_params: *lk
  flann_params: !!python/none None
  k_min_features: !!python/int 1600
  toggle_morphology: !!python/bool False

EXPERIMENT_3:
  name: !!python/str 'ORB-BRIEF-FLANN'
  correspondence_method: !!python/str 'matching'
  detector: !!python/str 'ORB'
  detector_params: *orb
  extractor: !!python/str 'BRIEF'
  extractor_params: *brief
  lk_params: !!python/none None
  flann_params: *flann-not-sift
  k_min_features: !!python/none None
  toggle_morphology: !!python/bool True

EXPERIMENT_4:
  name: !!python/str 'ORB-SIFT-FLANN'
  correspondence_method: !!python/str 'matching'
  detector: !!python/str 'ORB'
  detector_params: *orb
  extractor: !!python/str 'SIFT'
  extractor_params: !!python/none None
  lk_params: !!python/none None
  flann_params: *flann-sift
  k_min_features: !!python/none None
  toggle_morphology: !!python/bool False

EXPERIMENT_5:
  name: !!python/str 'SIFT-SIFT-FLANN'
  correspondence_method: !!python/str 'matching'
  detector: !!python/str 'SIFT'
  detector_params: !!python/none None
  extractor: !!python/str 'SIFT'
  extractor_params: !!python/none None
  lk_params: !!python/none None
  flann_params: *flann-sift
  k_min_features: !!python/none None
  toggle_morphology: !!python/bool False

EXPERIMENT_6:
  name: !!python/str 'SIFT-BRIEF-FLANN'
  correspondence_method: !!python/str 'matching'
  detector: !!python/str 'SIFT'
  detector_params: !!python/none None
  extractor: !!python/str 'BRIEF'
  extractor_params: !!python/none None
  lk_params: !!python/none None
  flann_params: *flann-not-sift
  k_min_features: !!python/none None
  toggle_morphology: !!python/bool False