DEFAULTS: &defaults
  ANNOTATIONS: !!python/str './data/images_v1/eevee/transformed_eevee_v1.txt'
  IMAGES: !!python/str 'data/images_v1/eevee/renders_compressed/*.jpg'
  W: !!python/int 1920
  H: !!python/int 1080
  PIN_HOLE_PARAMS:
    fx: !!python/float 1263.1578
    fy: !!python/int 1125
    cx: !!python/int 960
    cy: !!python/int 540

SHI_TOMASI_PARAMS: &shi-tomasi
  maxCorners: !!python/int 5000
  qualityLevel: !!python/float 0.1
  minDistance: !!python/int 10
  blockSize: !!python/int 10

FAST_PARAMS: &fast
  threshold: !!python/int 10
  nonmaxSuppression: !!python/bool True

ORB_PARAMS: &orb
  nfeatures: !!python/int 5000

BRIEF_PARAMS: &brief
  use_orientation: !!python/bool True

SIFT_PARAMS: &sift
  nfeatures: !!python/int 5000
  nOctaveLayers: !!python/int 3
  contrastThreshold: !!python/float 0.04
  edgeThreshold: !!python/int 10
  sigma: !!python/float 1.6

CENSURE_PARAMS: &censure
  maxSize: !!python/int 45
  responseThreshold: !!python/int 30
  lineThresholdProjected: !!python/int 10
  lineThresholdBinarized: !!python/int 8
  suppressNonmaxSize: !!python/int 5

AKAZE_PARAMS: &akaze
#  extended: !!python/bool False
#  upright: !!python/bool False
  threshold: !!python/float 0.05
  nOctaves: !!python/int 3
  nOctaveLayers: !!python/int 3
#  diffusivity: !!python/int 1 # DIFF_PM_G2

LK_PARAMS: &lk
  winSize: !!python/tuple [21, 21]
  maxLevel: !!python/int 6
  criteria: !!python/tuple [2, 1, 30, 0.01]  # (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 30, 0.01)
  flags: !!python/int 8                    # cv2.OPTFLOW_LK_GET_MIN_EIGENVALS
  minEigThreshold: !!python/float 0.0001 # 1e-4

FLANN_PARAMS:
  NON_SIFT: &flann-not-sift
    index_params:
      algorithm: !!python/int 6
      table_number: !!python/int 6
      key_size: !!python/int 12
      multi_probe_level: !!python/int 1
    search_params:
      checks: !!python/int 50
  SIFT: &flann-sift
    index_params:
      algorithm: !!python/int 0
      trees: !!python/int 5
    search_params:
      checks: !!python/int 50


# Optical Flow (appearance-based)
AB_SHI:
  detector_params: *shi-tomasi
  extractor_params:
  lk_params: *lk
  flann_params:
  k_min_features: !!python/int 1200
  toggle_morphology: !!python/bool True
